const plotDataRawTada = [
    {
        "plot_no": "1",
        "plot_size": "400",
        "facing": "East (Commercial)",
        "plot_status": "EVERYONES",
        "customer_name": "EVERYONES",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "2",
        "plot_size": "601.38",
        "facing": "East (Commercial)",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "3",
        "plot_size": "504.01",
        "facing": "East (Commercial)",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "4",
        "plot_size": "463.23",
        "facing": "East (Commercial)",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "5",
        "plot_size": "341.24",
        "facing": "East (Commercial)",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "6",
        "plot_size": "315.14",
        "facing": "East (Commercial)",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "7",
        "plot_size": "289.05",
        "facing": "East (Commercial)",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "8",
        "plot_size": "262.95",
        "facing": "East (Commercial)",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "9",
        "plot_size": "230.86",
        "facing": "South - East (Commercial)",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "10",
        "plot_size": "239.91",
        "facing": "South - West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "11",
        "plot_size": "242.22",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "12",
        "plot_size": "242.22",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "13",
        "plot_size": "242.22",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "14",
        "plot_size": "242.22",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "15",
        "plot_size": "242.22",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "16",
        "plot_size": "242.22",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "17",
        "plot_size": "180.21",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "18",
        "plot_size": "19",
        "facing": "",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "19",
        "plot_size": "188.84",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "20",
        "plot_size": "183.27",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "21",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "22",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "23",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "24",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "25",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "26",
        "plot_size": "197.61",
        "facing": "South - West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "27",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "28",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "29",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "30",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "31",
        "plot_size": "166.6",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "32",
        "plot_size": "171.67",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "33",
        "plot_size": "311.32",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "34",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "35",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "36",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "37",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "38",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "39",
        "plot_size": "44",
        "facing": "",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "40",
        "plot_size": "197.61",
        "facing": "South - West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "41",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "42",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "43",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "44",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "45",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "46",
        "plot_size": "301.71",
        "facing": "West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "47",
        "plot_size": "257.72",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "48",
        "plot_size": "348.83",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "49",
        "plot_size": "199.93",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "50",
        "plot_size": "199.93",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "51",
        "plot_size": "199.93",
        "facing": "East",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "52",
        "plot_size": "199.93",
        "facing": "East",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "53",
        "plot_size": "199.93",
        "facing": "East",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "54",
        "plot_size": "199.93",
        "facing": "East",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "55",
        "plot_size": "199.93",
        "facing": "East",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "56",
        "plot_size": "197.61",
        "facing": "South - East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "57",
        "plot_size": "197.61",
        "facing": "South - West",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "58",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "59",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "60",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "61",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "62",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "63",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "64",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "65",
        "plot_size": "199.93",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "66",
        "plot_size": "177.8",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "67",
        "plot_size": "189.67",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "68",
        "plot_size": "183.27",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "69",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "70",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "71",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "72",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "73",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "74",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "75",
        "plot_size": "219.92",
        "facing": "East",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "76",
        "plot_size": "217.62",
        "facing": "South - East",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "77",
        "plot_size": "217.62",
        "facing": "South - West",
        "plot_status": "SOUMITH",
        "customer_name": "SOUMITH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "78",
        "plot_size": "219.92",
        "facing": "West",
        "plot_status": "SURESH",
        "customer_name": "SURESH",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "79",
        "plot_size": "219.92",
        "facing": "West",
        "plot_status": "PREM KUMAR",
        "customer_name": "PREM KUMAR",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "80",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "81",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "82",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "83",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "84",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "85",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "86",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "87",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "88",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "89",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "90",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "91",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "92",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "93",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "94",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "95",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "96",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "97",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "98",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "99",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "100",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "101",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "102",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "103",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "104",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "105",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "106",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "107",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "108",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "109",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "110",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "111",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "112",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "113",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "114",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "115",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "116",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "117",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "118",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "119",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "120",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "121",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "122",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "123",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "124",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "125",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "126",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "127",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "128",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "129",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "130",
        "plot_size": "200",
        "facing": "East",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    },
    {
        "plot_no": "131",
        "plot_size": "200",
        "facing": "West",
        "plot_status": "AVAILABLE",
        "customer_name": "",
        "reference_name": "",
        "dim_north": "-",
        "dim_south": "-",
        "dim_east": "-",
        "dim_west": "-"
    }
];
